---
- name: search for stowed gits
  command: ls {{ stow_directories }}
  register: stowed_gits

- name: unstow all git versions
  shell: chdir={{ stow_directories }} stow --delete git*
  when: "'git' in stowed_gits.stdout"

- name: link latest git to stow
  shell: chdir={{ stow_directories }} stow "git_{{ git_version }}"
